# Generated by Django 5.2.5 on 2025-09-01 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='자기소개', max_length=500)),
                ('total_completed_days', models.IntegerField(default=0, help_text='총 완료한 일수')),
                ('current_streak', models.IntegerField(default=0, help_text='현재 연속 일수')),
                ('longest_streak', models.IntegerField(default=0, help_text='최장 연속 일수')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True, help_text='프로필 공개 여부')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_completed_days'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['follower', '-created_at'], name='accounts_fo_followe_592424_idx'), models.Index(fields=['following', '-created_at'], name='accounts_fo_followi_0cee87_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_complete', '첫 완독'), ('streak_7', '7일 연속'), ('streak_30', '30일 연속'), ('streak_100', '100일 연속'), ('total_30', '누적 30일'), ('total_100', '누적 100일'), ('total_365', '누적 365일'), ('book_complete', '책 완독'), ('testament_complete', '구약/신약 완독'), ('bible_complete', '성경 완독')], max_length=50)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('milestone_value', models.IntegerField(default=0, help_text='달성 값 (예: 연속 일수)')),
                ('details', models.JSONField(blank=True, default=dict, help_text='추가 정보')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achieved_at'],
                'unique_together': {('user', 'achievement_type')},
            },
        ),
    ]
