# Generated by Django 5.2.9 on 2026-01-12 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_default_entry_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='이메일 인증 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_usable_password_flag',
            field=models.BooleanField(default=False, help_text='사용자가 비밀번호를 설정했는지 여부 (소셜 전용 계정은 False)'),
        ),
        migrations.AlterField(
            model_name='userreadingsettings',
            name='font_family',
            field=models.CharField(choices=[('ridi-batang', 'RIDI 바탕'), ('noto-serif', 'Noto Serif KR'), ('kopub-batang', 'KoPub 바탕'), ('pretendard', 'Pretendard'), ('noto-sans', 'Noto Sans KR'), ('system', '시스템 기본')], default='kopub-batang', help_text='글꼴', max_length=20),
        ),
        migrations.AlterField(
            model_name='userreadingsettings',
            name='font_weight',
            field=models.CharField(choices=[('normal', '보통'), ('medium', '중간'), ('bold', '굵게')], default='medium', help_text='글자 두께', max_length=10),
        ),
        migrations.AlterField(
            model_name='userreadingsettings',
            name='line_height',
            field=models.FloatField(default=1.6, help_text='줄 간격 (1.4-2.4)'),
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('kakao', '카카오'), ('google', '구글')], max_length=20)),
                ('provider_id', models.CharField(help_text='소셜 제공자의 고유 ID', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='소셜 계정 이메일', max_length=254, null=True)),
                ('profile_image', models.URLField(blank=True, max_length=500, null=True)),
                ('access_token', models.TextField(blank=True, help_text='액세스 토큰 (암호화 저장)', null=True)),
                ('refresh_token', models.TextField(blank=True, help_text='리프레시 토큰 (암호화 저장)', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='추가 프로필 정보')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'provider'], name='accounts_so_user_id_0a462a_idx'), models.Index(fields=['provider', 'provider_id'], name='accounts_so_provide_f59f70_idx')],
                'unique_together': {('provider', 'provider_id')},
            },
        ),
    ]
