# Generated by Django 5.1.6 on 2025-02-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybibleschedule',
            name='guide_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
