# Generated by Django 5.1.6 on 2025-02-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_dailybibleschedule_guide_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbibleprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbibleprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
