# Generated by Django 5.1.6 on 2025-02-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_userbibleprogress_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailybibleschedule',
            unique_together=set(),
        ),
    ]
