# Generated by Django 5.1.6 on 2025-03-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_biblereadingplan_hasenarecord_plansubscription_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanSubscription',
        ),
    ]
