# Generated by Django 5.1.6 on 2025-03-10 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_dailybibleschedule_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybibleschedule',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='todos.biblereadingplan'),
        ),
    ]
