# Generated by Django 5.1.6 on 2025-03-10 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_alter_dailybibleschedule_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbibleprogress',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='userbibleprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userbibleprogress',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='todos.dailybibleschedule'),
        ),
        migrations.AddField(
            model_name='userbibleprogress',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='todos.plansubscription'),
        ),
    ]
