# Generated by Django 5.1.6 on 2025-03-10 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_alter_userbibleprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbibleprogress',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='todos.dailybibleschedule'),
        ),
        migrations.AlterField(
            model_name='userbibleprogress',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='todos.plansubscription'),
        ),
    ]
