# Generated by Django 5.1.6 on 2025-03-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_alter_userbibleprogress_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbibleprogress',
            name='book',
        ),
        migrations.RemoveField(
            model_name='userbibleprogress',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userbibleprogress',
            name='last_chapter_read',
        ),
        migrations.RemoveField(
            model_name='userbibleprogress',
            name='user',
        ),
    ]
