# Generated by Django 5.2.8 on 2025-11-24 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0014_readinggroup_groupmembership_groupinvitation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='readinggroup',
            name='todos_readi_plan_id_717955_idx',
        ),
        migrations.RemoveField(
            model_name='readinggroup',
            name='plan',
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='plans',
            field=models.ManyToManyField(help_text='그룹이 따르는 읽기 플랜들 (복수 선택 가능)', related_name='reading_groups', to='todos.biblereadingplan'),
        ),
        migrations.AddIndex(
            model_name='readinggroup',
            index=models.Index(fields=['is_public'], name='todos_readi_is_publ_8b6efc_idx'),
        ),
    ]
