# Generated by Django 5.2.8 on 2025-12-02 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0015_remove_readinggroup_todos_readi_plan_id_717955_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlanDisplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#3B82F6', help_text='플랜 표시 색상 (HEX)', max_length=7)),
                ('display_order', models.IntegerField(default=0, help_text='캘린더에서 표시 순서')),
                ('is_visible', models.BooleanField(default=True, help_text='캘린더에 표시 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display_settings', to='todos.plansubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_display_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '플랜 표시 설정',
                'verbose_name_plural': '플랜 표시 설정',
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['user', 'is_visible'], name='todos_userp_user_id_eefadf_idx')],
            },
        ),
    ]
