# Generated by Django 5.2.8 on 2025-12-02 00:37

from django.db import migrations

PLAN_COLORS = [
    '#3B82F6',  # Blue (기본)
    '#10B981',  # Green
    '#F59E0B',  # Amber
    '#EF4444',  # Red
    '#8B5CF6',  # Purple
    '#EC4899',  # Pink
    '#06B6D4',  # Cyan
    '#F97316',  # Orange
]


def populate_display_settings(apps, schema_editor):
    """기존 구독에 대한 표시 설정 생성"""
    PlanSubscription = apps.get_model('todos', 'PlanSubscription')
    UserPlanDisplaySettings = apps.get_model('todos', 'UserPlanDisplaySettings')

    # 사용자별로 그룹화
    user_subscriptions = {}
    for subscription in PlanSubscription.objects.all():
        user_id = subscription.user_id
        if user_id not in user_subscriptions:
            user_subscriptions[user_id] = []
        user_subscriptions[user_id].append(subscription)

    # 각 사용자의 구독에 대해 설정 생성
    for user_id, subscriptions in user_subscriptions.items():
        for idx, subscription in enumerate(subscriptions):
            # 이미 설정이 있는지 확인
            if not UserPlanDisplaySettings.objects.filter(subscription=subscription).exists():
                UserPlanDisplaySettings.objects.create(
                    user_id=user_id,
                    subscription=subscription,
                    color=PLAN_COLORS[idx % len(PLAN_COLORS)],
                    display_order=idx,
                    is_visible=True
                )


def reverse_populate(apps, schema_editor):
    """롤백 시 생성된 설정 삭제"""
    UserPlanDisplaySettings = apps.get_model('todos', 'UserPlanDisplaySettings')
    UserPlanDisplaySettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0016_add_user_plan_display_settings'),
    ]

    operations = [
        migrations.RunPython(populate_display_settings, reverse_populate),
    ]
