# Generated by Django 5.2.9 on 2026-01-03 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0017_populate_existing_display_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='show_in_profile',
            field=models.BooleanField(default=True, help_text='프로필에 이 그룹 표시 여부'),
        ),
        migrations.CreateModel(
            name='UserReadingPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(help_text='성경책 코드 (gen, exo...)', max_length=10)),
                ('chapter', models.IntegerField(help_text='장 번호')),
                ('verse', models.IntegerField(blank=True, help_text='절 번호 (선택)', null=True)),
                ('scroll_position', models.FloatField(default=0, help_text='스크롤 위치 (0-1)')),
                ('version', models.CharField(default='GAE', help_text='역본', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_position', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '읽기 위치',
                'verbose_name_plural': '읽기 위치',
            },
        ),
        migrations.CreateModel(
            name='BibleBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_type', models.CharField(choices=[('chapter', '장'), ('verse', '절')], max_length=10)),
                ('book', models.CharField(help_text='성경책 코드', max_length=10)),
                ('chapter', models.IntegerField()),
                ('start_verse', models.IntegerField(blank=True, help_text='시작 절', null=True)),
                ('end_verse', models.IntegerField(blank=True, help_text='끝 절', null=True)),
                ('title', models.CharField(blank=True, help_text='북마크 제목', max_length=100)),
                ('color', models.CharField(default='#3B82F6', help_text='표시 색상', max_length=7)),
                ('memo', models.TextField(blank=True, help_text='간단한 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '북마크',
                'verbose_name_plural': '북마크',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'book', 'chapter'], name='todos_bible_user_id_72d627_idx'), models.Index(fields=['user', 'bookmark_type'], name='todos_bible_user_id_9943e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonalReadingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(help_text='성경책 코드', max_length=10)),
                ('chapter', models.IntegerField()),
                ('read_date', models.DateField(help_text='읽은 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_reading_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '개인 읽기 기록',
                'verbose_name_plural': '개인 읽기 기록',
                'indexes': [models.Index(fields=['user', 'book'], name='todos_perso_user_id_069c86_idx'), models.Index(fields=['user', 'read_date'], name='todos_perso_user_id_1ecc97_idx')],
                'unique_together': {('user', 'book', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='ReflectionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(help_text='성경책 코드', max_length=10)),
                ('chapter', models.IntegerField()),
                ('start_verse', models.IntegerField(blank=True, null=True)),
                ('end_verse', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(help_text='묵상 내용')),
                ('is_private', models.BooleanField(default=True, help_text='비공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '묵상노트',
                'verbose_name_plural': '묵상노트',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'book', 'chapter'], name='todos_refle_user_id_5c9064_idx'), models.Index(fields=['user', '-created_at'], name='todos_refle_user_id_9980e1_idx')],
            },
        ),
    ]
