# Generated by Django 5.2.9 on 2026-01-03 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0018_bible_reading_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatchupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='사용자 지정 이름 (예: 나의 1월 도전!)', max_length=100)),
                ('range_start', models.DateField(help_text='밀린 기간 시작일')),
                ('range_end', models.DateField(help_text='밀린 기간 종료일')),
                ('strategy', models.CharField(choices=[('parallel', '동시 진행'), ('sequential', '순차 복귀')], default='parallel', help_text='동시 진행: 원본과 함께 / 순차 복귀: 밀린 것부터 순서대로', max_length=20)),
                ('target_rejoin_date', models.DateField(blank=True, help_text='순차 복귀 모드에서 원본 플랜 합류 목표일', null=True)),
                ('max_daily_readings', models.IntegerField(blank=True, help_text='하루 최대 읽기 횟수', null=True)),
                ('max_daily_chapters', models.IntegerField(blank=True, help_text='하루 최대 읽기 장 수', null=True)),
                ('weekend_multiplier', models.DecimalField(decimal_places=1, default=1.0, help_text='주말 읽기량 배수 (예: 1.5 = 평일의 1.5배)', max_digits=3)),
                ('status', models.CharField(choices=[('active', '진행 중'), ('completed', '완료'), ('abandoned', '포기')], default='active', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(help_text='따라잡기 대상 구독', on_delete=django.db.models.deletion.CASCADE, related_name='catchup_sessions', to='todos.plansubscription')),
            ],
            options={
                'verbose_name': '따라잡기 세션',
                'verbose_name_plural': '따라잡기 세션',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatchupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(help_text='새로 배정된 날짜')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_schedule', models.ForeignKey(help_text='원본 스케줄 참조', on_delete=django.db.models.deletion.CASCADE, to='todos.dailybibleschedule')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='todos.catchupsession')),
            ],
            options={
                'verbose_name': '따라잡기 스케줄',
                'verbose_name_plural': '따라잡기 스케줄',
                'ordering': ['scheduled_date', 'original_schedule__date'],
            },
        ),
        migrations.AddIndex(
            model_name='catchupsession',
            index=models.Index(fields=['subscription', 'status'], name='todos_catch_subscri_8cf86b_idx'),
        ),
        migrations.AddIndex(
            model_name='catchupschedule',
            index=models.Index(fields=['session', 'scheduled_date'], name='todos_catch_session_c0dd70_idx'),
        ),
        migrations.AddIndex(
            model_name='catchupschedule',
            index=models.Index(fields=['session', 'is_completed'], name='todos_catch_session_381329_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='catchupschedule',
            unique_together={('session', 'original_schedule')},
        ),
    ]
