# Generated by Django 5.2.9 on 2026-01-06 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0019_catchup_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(help_text='성경책 코드', max_length=10)),
                ('chapter', models.IntegerField()),
                ('start_verse', models.IntegerField()),
                ('end_verse', models.IntegerField()),
                ('color', models.CharField(default='#FEF3C7', help_text='하이라이트 색상 (HEX)', max_length=7)),
                ('memo', models.TextField(blank=True, help_text='간단한 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '하이라이트',
                'verbose_name_plural': '하이라이트',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='biblebookmark',
            constraint=models.UniqueConstraint(condition=models.Q(('bookmark_type', 'chapter')), fields=('user', 'book', 'chapter'), name='unique_chapter_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='biblebookmark',
            constraint=models.UniqueConstraint(condition=models.Q(('bookmark_type', 'verse')), fields=('user', 'book', 'chapter', 'start_verse', 'end_verse'), name='unique_verse_bookmark'),
        ),
        migrations.AddField(
            model_name='biblehighlight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_highlights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='biblehighlight',
            index=models.Index(fields=['user', 'book', 'chapter'], name='todos_bible_user_id_060091_idx'),
        ),
        migrations.AddIndex(
            model_name='biblehighlight',
            index=models.Index(fields=['user', '-created_at'], name='todos_bible_user_id_b8251a_idx'),
        ),
    ]
