# Generated by Django 5.2.9 on 2026-01-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0020_add_bookmark_unique_constraints'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailybibleschedule',
            index=models.Index(fields=['plan', 'date'], name='schedule_plan_date_idx'),
        ),
        migrations.AddIndex(
            model_name='userbibleprogress',
            index=models.Index(fields=['subscription', 'is_completed'], name='progress_sub_completed_idx'),
        ),
    ]
