# Generated by Django 5.2.9 on 2026-01-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleContentCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='캐시 키 (version:book:chapter 형식)', max_length=100, unique=True)),
                ('version', models.CharField(db_index=True, help_text='번역본 (GAE, KNT, HAN, SAE, SAENEW, COG, COGNEW)', max_length=20)),
                ('book', models.CharField(db_index=True, help_text='성경책 코드 (gen, exo, mat 등)', max_length=10)),
                ('chapter', models.IntegerField(help_text='장 번호')),
                ('content', models.TextField(help_text='원본 HTML/JSON 콘텐츠')),
                ('content_type', models.CharField(choices=[('html', 'HTML'), ('json', 'JSON')], default='html', help_text='콘텐츠 타입', max_length=10)),
                ('source_url', models.URLField(blank=True, help_text='원본 URL', max_length=500)),
                ('fetch_success', models.BooleanField(default=True, help_text='마지막 fetch 성공 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '성경 본문 캐시',
                'verbose_name_plural': '성경 본문 캐시',
                'ordering': ['version', 'book', 'chapter'],
                'indexes': [models.Index(fields=['version', 'book', 'chapter'], name='bible_cache_version_6ef8d6_idx')],
            },
        ),
    ]
